# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c53bff99838ebe0e6b4a2414d97d47b863ef1ccaea2c47d70f6a7dd73d00faf26faf96f9bbca5dd5a111985c8341e6a678c53d5d8dcab840475f6b74cbd6a0a1

test:
  secret_key_base: 7c270bf4ee490967774bc1680463224d414d1ece1bd1b6459e26b6cedfe35977ca5d5090ab464a19a258e4f65bbf29d90ddd9bc4402a5be74894f513299d9589

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
